-- MySQL Script generated by MySQL Workbench
-- Fri Feb 23 15:34:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gsella_151
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gsella_151
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gsella_151` DEFAULT CHARACTER SET utf8mb3 ;
USE `gsella_151` ;

-- -----------------------------------------------------
-- Table `gsella_151`.`t_planete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gsella_151`.`t_planete` (
  `PK_Planete` INT NOT NULL,
  `Nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Planete`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gsella_151`.`t_superhero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gsella_151`.`t_superhero` (
  `PK_Superhero` INT NOT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `Image` VARCHAR(45) NULL DEFAULT NULL,
  `FK_Planete` INT NOT NULL,
  PRIMARY KEY (`PK_Superhero`),
  INDEX `fk_T_Superhero_T_Planete1_idx` (`FK_Planete` ASC) VISIBLE,
  CONSTRAINT `fk_T_Superhero_T_Planete1`
    FOREIGN KEY (`FK_Planete`)
    REFERENCES `gsella_151`.`t_planete` (`PK_Planete`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gsella_151`.`t_superpouvoir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gsella_151`.`t_superpouvoir` (
  `PK_SuperPouvoir` INT NOT NULL,
  `Nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_SuperPouvoir`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gsella_151`.`t_mdp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gsella_151`.`t_mdp` (
  `PK_Mdp` INT NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PK_Mdp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gsella_151`.`t_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gsella_151`.`t_utilisateur` (
  `PK_Utilisateur` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `FK_Mdp` INT NOT NULL,
  PRIMARY KEY (`PK_Utilisateur`),
  INDEX `fk_t_utilisateur_t_mdp1_idx` (`FK_Mdp` ASC) VISIBLE,
  CONSTRAINT `fk_t_utilisateur_t_mdp1`
    FOREIGN KEY (`FK_Mdp`)
    REFERENCES `gsella_151`.`t_mdp` (`PK_Mdp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `gsella_151`.`tr_superhero_superpouvoir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gsella_151`.`tr_superhero_superpouvoir` (
  `PFK_Superhero` INT NOT NULL,
  `PFK_Superpouvoir` INT NOT NULL,
  PRIMARY KEY (`PFK_Superhero`, `PFK_Superpouvoir`),
  INDEX `fk_TR_Superhero_Superpouvoir_T_Superhero1_idx` (`PFK_Superhero` ASC) VISIBLE,
  INDEX `fk_TR_Superhero_Superpouvoir_T_Superpouvoir1_idx` (`PFK_Superpouvoir` ASC) VISIBLE,
  CONSTRAINT `fk_TR_Superhero_Superpouvoir_T_Superhero1`
    FOREIGN KEY (`PFK_Superhero`)
    REFERENCES `gsella_151`.`t_superhero` (`PK_Superhero`),
  CONSTRAINT `fk_TR_Superhero_Superpouvoir_T_Superpouvoir1`
    FOREIGN KEY (`PFK_Superpouvoir`)
    REFERENCES `gsella_151`.`t_superpouvoir` (`PK_SuperPouvoir`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
